export const ORGAN_TYPES = {
    AO: "Aorta",
    BL: "Bladder",
    BD: "Blood",
    BM: "Bone Marrow",
    BR: "Brain",
    LB: "Bronchus (Left)",
    RB: "Bronchus (Right)",
    LE: "Eye (Left)",
    RE: "Eye (Right)",
    LF: "Fallopian Tube (Left)",
    RF: "Fallopian Tube (Right)",
    HT: "Heart",
    LK: "Kidney (Left)",
    RK: "Kidney (Right)",
    LI: "Large Intestine",
    LV: "Liver",
    LL: "Lung (Left)",
    RL: "Lung (Right)",
    LY: "Lymph Node",
    LO: "Ovary (Left)",
    RO: "Ovary (Right)",
    PA: "Pancreas",
    PL: "Placenta",
    SI: "Small Intestine",
    SK: "Skin",
    SP: "Spleen",
    ST: "Sternum",
    TH: "Thymus",
    TR: "Trachea",
    UR: "Ureter",
    UT: "Uterus",
    OT: "Other"
};
